bind = "0.0.0.0:25566"
welcome_message = "§4Welcome to Dunder Mifflin"
action_bar = "§4Welcome to Dunder Mifflin"
default_game_mode = "spectator"
hardcore = false
fetch_player_skins = false
reduced_debug_info = false
allow_unsupported_versions = false

[forwarding]
method = "BUNGEE_GUARD"
tokens = ["jwwHMfQEFWt0"]

[world]
spawn_position = [
    0.0,
    200.0,
    0.0,
]
spawn_rotation = [
    0.0,
    0.0,
]
dimension = "end"
time = "day"

[world.experimental]
view_distance = 1
schematic_file = ""
lock_time = true

[world.boundaries]
enabled = true
min_y = 0
teleport_message = "<red>You have reached the bottom of the world.</red>"

[server_list]
reply_to_status = true
max_players = 20
message_of_the_day = "A Minecraft Server"
show_online_player_count = true
server_icon = "server-icon.png"

[compression]
threshold = -1
level = 6

[tab_list]
enabled = true
header = "<bold>§4Welcome to Dunder Mifflin</bold>"
footer = "<green>Enjoy your stay!</green>"
player_listed = true

[boss_bar]
enabled = false
title = "<bold>Welcome to Dunder Mifflin</bold>"
health = 1.0
color = "pink"
division = 0

[title]
enabled = false
title = "<bold>§4Welcome!</bold>"
subtitle = "§4Enjoy your stay"
fade_in = 10
stay = 70
fade_out = 20
