bind = "0.0.0.0:25566"
welcome_message = "Limbo"
action_bar = "Limbo"
default_game_mode = "spectator"
hardcore = false
fetch_player_skins = false
reduced_debug_info = false
allow_unsupported_versions = false

[forwarding]
method = "BUNGEE_GUARD"
tokens = ["token goes here"]

[world]
spawn_position = [
    0.0,
    200.0,
    0.0,
]
spawn_rotation = [
    0.0,
    0.0,
]
dimension = "end"
time = "day"

[world.experimental]
view_distance = 1
schematic_file = ""
lock_time = true

[world.boundaries]
enabled = true
min_y = 0
teleport_message = "<red>You have reached the bottom of the world.</red>"

[server_list]
reply_to_status = true
max_players = 20
message_of_the_day = "A Minecraft Server"
show_online_player_count = true
server_icon = "server-icon.png"

[compression]
threshold = -1
level = 6

[tab_list]
enabled = true
header = "<bold>Limbo</bold>"
footer = "<green>Enjoy your stay!</green>"
player_listed = true

[boss_bar]
enabled = false
title = "<bold>Limbo</bold>"
health = 1.0
color = "pink"
division = 0

[title]
enabled = false
title = "<bold>ยง4Welcome!</bold>"
subtitle = "ยง4Enjoy your stay"
fade_in = 10
stay = 70
fade_out = 20
